### ISSUE TITLE
[Installing] failed when installing via CocoaPod

### ISSUE THREAD

**Issue by lengocduy** [lengocduy/swift-log#5]
- [x] Wrong the guide line in the Podfile: **pod 'Logging', :git => 'https://github.com/lengocduy/swift-log.git', :branch => 'master'**
- [x] When we specify a specific branch master. The error comes **Specs satisfying the `Logging (from `https://github.com/lengocduy/swift-log.git`, branch `master`)` dependency were found, but they required a higher minimum deployment target.**

**Comment by TuananhSteven** [comment]
The problem is The developer declare the target less than supported of framework.
in the Podfile> platform :ios, '9.0'. Item 2 should be resolve.

**Comment by lengocduy** [comment]
> The problem is The developer declare the target less than supported of framework.
> in the Podfile> platform :ios, '9.0'. Item 2 should be resolve.

Thanks for your quick feedback

**Comment by lengocduy** [comment]
Update README to use default **master** branch.
in Podfile: **pod 'Logging', :git => 'https://github.com/lengocduy/swift-log.git'**
